name: sketchide
description: "SketchIDE create cross platform applocation."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  path_provider: ^2.1.5 # Scope Storage path
  flutter_native_splash: ^2.4.3 # Splash Screen
  logging: ^1.2.0 # file serve
  sqflite: ^2.4.1
  path: ^1.9.0
  get: ^4.6.6
  image_picker: ^1.1.2
  image: ^4.3.0
  url_launcher: ^6.3.1
  uuid: ^4.5.1
  provider: ^6.1.2
  file_picker: ^8.0.0+1
  archive: ^3.4.10
  permission_handler: ^11.3.1
  device_info_plus: ^10.1.0
  flutter_highlight: ^0.7.0
  highlight: ^0.7.0
  yaml: ^3.1.2
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.1
  change_app_package_name: ^1.4.0

flutter_icons: # Moved outside of the 'flutter' section
  android: true
  ios: true
  image_path: "assets/icon.png" # Path to your main icon image

flutter:
  uses-material-design: true
